/*
 * Created on 2025-02-08 ( 14:50:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.thirtParty.telosys.rest.services;

import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.example.backend.thirtParty.telosys.persistence.entities.Authors;
import com.example.backend.thirtParty.telosys.persistence.repositories.AuthorsRepository;
import com.example.backend.thirtParty.telosys.rest.dto.AuthorsDTO;
import com.example.backend.thirtParty.telosys.rest.services.commons.GenericService;

/**
 * REST service for entity "Authors" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * 
 * @author Telosys
 *
 */
@Service
public class AuthorsService extends GenericService<Authors, AuthorsDTO> {

	private static final Logger logger = LoggerFactory.getLogger(AuthorsService.class);

	private final AuthorsRepository repository; // injected by constructor

	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 */
	public AuthorsService(AuthorsRepository repository) {
		super(Authors.class, AuthorsDTO.class);
		this.repository = repository;
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private Long getEntityId(AuthorsDTO dto) {
		return dto.getId();
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<AuthorsDTO> findAll() {
		logger.debug("findAll()");
		Iterable<Authors> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param id 
	 * @return the entity or null if not found
	 */
	public AuthorsDTO findById(Long id) {
		Long entityId = id;
		logger.debug("findById({})", entityId);
		Optional<Authors> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist)
	 *
	 * @param id 
	 * @param dto 
	 */
	public void save(Long id, AuthorsDTO dto) {
		Long entityId = id;
		logger.debug("save({},{})", entityId, dto);
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setId(id);
		repository.save(dtoToEntity(dto));
	}
	/**
	 * Saves a list of entities
	 *
	 * @param dtos
	 */
	public void saveAll(List<AuthorsDTO> dtos) {
		logger.debug("saveList({})", dtos);
		List<Authors> entities = dtoListToEntityList(dtos);
		repository.saveAll(entities);
	}
	/**
	 * Updates the given entity if it exists
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(AuthorsDTO dto) {
		logger.debug("update({})", dto);
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists
	 *
	 * @param id 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(Long id, AuthorsDTO dto) {
		Long entityId = id;
		logger.debug("partialUpdate({}, {})", entityId, dto);
		Optional<Authors> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			Authors entity = optionalEntity.get();
			// implement here the partial update
			// entity.setXxx(dto.getXxx());
			// etc ...
			repository.save(entity);
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(AuthorsDTO dto) {
		logger.debug("create({})", dto);
		// auto-generated Primary Key
		repository.save(dtoToEntity(dto));
		return true; // always created
	}

	/**
	 * Deletes an entity by its PK
	 *
	 * @param id 
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(Long id) {
		Long entityId = id;
		logger.debug("deleteById({})", entityId);
		if (repository.existsById(entityId)) {
			repository.deleteById(entityId);
			return true; // find and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders"
	// -----------------------------------------------------------------------------------------
/***
	public List<AuthorsDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		// List<Authors> list = repository.findByTitle(title);
		List<Authors> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<AuthorsDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		// List<Authors> list = repository.findByTitle(title);
		List<Authors> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}

	public List<AuthorsDTO> findByTitleAndPrice(String title, BigDecimal price) {
		logger.debug("findByTitleAndPrice({}, {})", title, price);
		List<Authors> list = repository.findByTitleContainingAndPrice(title, price);
		return entityListToDtoList(list);
	}
***/
}
