/*
 * Created on 2025-02-20 ( 20:11:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.thirtParty.telosys.rest.services;

import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.example.backend.thirtParty.telosys.persistence.entities.ShippingInfo;
import com.example.backend.thirtParty.telosys.persistence.repositories.ShippingInfoRepository;
import com.example.backend.thirtParty.telosys.rest.dto.ShippingInfoDTO;
import com.example.backend.thirtParty.telosys.rest.services.commons.GenericService;

/**
 * REST service for entity "ShippingInfo" <br>
 * 
 * This service provides all the necessary operations required by the REST
 * controller <br>
 * 
 * @author Telosys
 *
 */
@Service
public class ShippingInfoService extends GenericService<ShippingInfo, ShippingInfoDTO> {

	private static final Logger logger = LoggerFactory.getLogger(ShippingInfoService.class);

	private final ShippingInfoRepository repository; // injected by constructor

	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 */
	public ShippingInfoService(ShippingInfoRepository repository) {
		super(ShippingInfo.class, ShippingInfoDTO.class);
		this.repository = repository;
	}

	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private Long getEntityId(ShippingInfoDTO dto) {
		return dto.getId();
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<ShippingInfoDTO> findAll() {
		logger.debug("findAll()");
		Iterable<ShippingInfo> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param id
	 * @return the entity or null if not found
	 */
	public ShippingInfoDTO findById(long id) {
		Long entityId = id;
		logger.debug("findById({})", entityId);
		Optional<ShippingInfo> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist)
	 *
	 * @param id
	 * @param dto
	 */
	public void save(long id, ShippingInfoDTO dto) {
		Long entityId = id;
		logger.debug("save({},{})", entityId, dto);
		// force PK in DTO (just to be sure to conform with the given PK)
		dto.setId(id);
		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(ShippingInfoDTO dto) {
		logger.debug("update({})", dto);
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists
	 *
	 * @param id
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(long id, ShippingInfoDTO dto) {
		Long entityId = id;
		logger.debug("partialUpdate({}, {})", entityId, dto);
		Optional<ShippingInfo> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			ShippingInfo entity = optionalEntity.get();
			// implement here the partial update
			// entity.setXxx(dto.getXxx());
			// etc ...
			repository.save(entity);
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(ShippingInfoDTO dto) {
		logger.debug("create({})", dto);
		// auto-generated Primary Key
		if (repository.existsById(dto.getId())) {
			return update(dto);
		} else {
			repository.save(new ShippingInfo(dto));
			return true; // always created
		}
	}

	/**
	 * Deletes an entity by its PK
	 *
	 * @param id
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(long id) {
		Long entityId = id;
		logger.debug("deleteById({})", entityId);
		if (repository.existsById(entityId)) {
			repository.deleteById(entityId);
			return true; // find and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	/**
	 * Finds all ShippingInfo entities by user ID
	 *
	 * @param userId
	 * @return list of ShippingInfoDTO
	 */
	public List<ShippingInfoDTO> findByUserId(long userId) {
		logger.debug("findByUserId({})", userId);
		List<ShippingInfo> list = repository.findByUserId(userId);
		return entityListToDtoList(list);
	}
	// -----------------------------------------------------------------------------------------
	// Specific "finders"
	// -----------------------------------------------------------------------------------------
	/***
	 * public List<ShippingInfoDTO> findByTitle(String title) {
	 * logger.debug("findByTitle({})", title);
	 * // List<ShippingInfo> list = repository.findByTitle(title);
	 * List<ShippingInfo> list = repository.findByTitleContaining(title);
	 * return entityListToDtoList(list);
	 * }
	 * 
	 * public List<ShippingInfoDTO> findByPrice(BigDecimal price) {
	 * logger.debug("findByPrice({})", price);
	 * // List<ShippingInfo> list = repository.findByTitle(title);
	 * List<ShippingInfo> list = repository.findByPrice(price);
	 * return entityListToDtoList(list);
	 * }
	 * 
	 * public List<ShippingInfoDTO> findByTitleAndPrice(String title, BigDecimal
	 * price) {
	 * logger.debug("findByTitleAndPrice({}, {})", title, price);
	 * List<ShippingInfo> list = repository.findByTitleContainingAndPrice(title,
	 * price);
	 * return entityListToDtoList(list);
	 * }
	 ***/
}
