version: '2'
services:
  be:
    image: shegga/phung_be:jenkins
    container_name: phung_be
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - DATABASE_HOST=172.22.0.3
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=3306
      - ALLOWED_ORIGINS=localhost:3000
      - BASE_URL=https://47.129.38.106:8080
    networks:
      - app_net


  # jenkins:
  #   image: jenkins/jenkins:lts
  #   privileged: true
  #   user: root
  #   ports:
  #     - 8080:8080
  #     - 50000:50000
  #   container_name: jenkins
  #   volumes:
  #     - ~/jenkins:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /usr/bin/docker:/usr/bin/docker
  #     - /usr/libexec/docker/cli-plugins:/usr/libexec/docker/cli-plugins
  #   networks:
  #     - app_net

networks:
  app_net:
    driver: bridge
volumes:
  starter_kit_db:
