services:
  be:
    image: shegga/phung_be:0.0.7
    container_name: phung_be
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - DATABASE_HOST=172.19.0.3
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=3306
      - ALLOWED_ORIGINS=localhost:3000
      - BASE_URL=https://47.129.38.106:8080
    networks:
      - app_net