package com.example.backend.thirtParty.telosys.rest.dto;

/*
 * Created on 2025-02-21 ( 17:39:25 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */

import java.io.Serializable;
import java.time.LocalDateTime;

import com.example.backend.util.Client;

/**
 * DTO class for "CartItem"
 *
 * @author Telosys
 *
 */
@Client
public class CartItemDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- PRIMARY KEY
    private long bookId;
    private long userId;
    // --- OTHER DATA FIELDS
    private LocalDateTime createdAt;
    private int quantity;
    // --- LINKS ( RELATIONSHIPS )
    private BooksDTO books;
    private UserDTO user;

    /**
     * Constructor
     */
    public CartItemDTO() {
        super();
    }

    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    public long getBookId() {
        return this.bookId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public int getQuantity() {
        return this.quantity;
    }

    public BooksDTO getBooks() {
        return this.books;
    }

    public UserDTO getUser() {
        return this.user;
    }

    @Override
    public String toString() {
        String separator = "|";
        StringBuilder sb = new StringBuilder();
        sb.append("CartItem[");
        sb.append("bookId=").append(bookId);
        sb.append(separator).append("userId=").append(userId);
        sb.append(separator).append("createdAt=").append(createdAt);
        sb.append(separator).append("quantity=").append(quantity);
        sb.append("]");
        return sb.toString();
    }
}
