/*
 * Created on 2025-02-08 ( 14:50:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.thirtParty.telosys.rest.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;


/**
 * DTO class for "Orders"
 *
 * @author Telosys
 *
 */
public class OrdersResponseDTO implements Serializable {
    private List<OrdersDTO> ordersDTO;
    private BigDecimal cost;
    private BigDecimal remain;
    private String message;
    private int status;

    public OrdersResponseDTO(String message, int status) {
        this.message = message;
        this.status = status;
    }

    public OrdersResponseDTO(List<OrdersDTO> ordersDTO, BigDecimal cost, BigDecimal remain, String message,
            int status) {
        this.ordersDTO = ordersDTO;
        this.cost = cost;
        this.remain = remain;
        this.message = message;
        this.status = status;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public BigDecimal getCost() {
        return cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    public BigDecimal getRemain() {
        return remain;
    }

    public void setRemain(BigDecimal remain) {
        this.remain = remain;
    }

    public List<OrdersDTO> getOrdersDTO() {
        return ordersDTO;
    }

    public void setOrdersDTO(List<OrdersDTO> ordersDTO) {
        this.ordersDTO = ordersDTO;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

}
