package com.example.backend.thirtParty.telosys.rest.dto;

/*
 * Created on 2025-02-21 ( 17:39:25 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * DTO class for "User"
 *
 * @author Telosys
 *
 */
public class UserDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- PRIMARY KEY
    private long id;
    // --- OTHER DATA FIELDS
    private String email;
    private String firstName;
    private String lastName;
    private String password;
    private String profileImageUrl;
    private String role;
    private boolean verified;
    private BigDecimal balance;

    /**
     * Constructor
     */
    public UserDTO() {
        super();
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getId() {
        return this.id;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return this.email;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword() {
        return this.password;
    }

    public void setProfileImageUrl(String profileImageUrl) {
        this.profileImageUrl = profileImageUrl;
    }

    public String getProfileImageUrl() {
        return this.profileImageUrl;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getRole() {
        return this.role;
    }

    public void setVerified(boolean verified) {
        this.verified = verified;
    }

    public boolean isVerified() {
        return this.verified;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    @Override
    public String toString() {
        String separator = "|";
        StringBuilder sb = new StringBuilder();
        sb.append("User[");
        sb.append("id=").append(id);
        sb.append(separator).append("email=").append(email);
        sb.append(separator).append("firstName=").append(firstName);
        sb.append(separator).append("lastName=").append(lastName);
        sb.append(separator).append("password=").append(password);
        sb.append(separator).append("profileImageUrl=").append(profileImageUrl);
        sb.append(separator).append("role=").append(role);
        sb.append(separator).append("verified=").append(verified);
        sb.append(separator).append("balance=").append(balance);
        sb.append("]");
        return sb.toString();
    }
}
