/*
 * Created on 2025-02-08 ( 14:50:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.telosys.persistence.entities;

import java.io.Serializable;

import com.example.backend.util.Client;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity class for "Authors"
 *
 * @author Telosys
 *
 */
@Entity
@Client
@Table(name = "authors", catalog = "starter-kit-db")
public class Authors implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    // --- OTHER DATA FIELDS
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    @Column(name = "gender")
    private Boolean gender;

    @Column(name = "birth_year")
    private Short birthYear;

    @Column(name = "death_year")
    private Short deathYear;
    /**
     * Constructor
     */
    public Authors() {
        super();
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return this.id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    public Boolean getGender() {
        return this.gender;
    }

    public void setBirthYear(Short birthYear) {
        this.birthYear = birthYear;
    }

    public Short getBirthYear() {
        return this.birthYear;
    }

    public void setDeathYear(Short deathYear) {
        this.deathYear = deathYear;
    }

    public Short getDeathYear() {
        return this.deathYear;
    }

    @Override
    public String toString() {
        String separator = "|";
        StringBuilder sb = new StringBuilder();
        sb.append("Authors[");
        sb.append("id=").append(id);
        sb.append(separator).append("name=").append(name);
        sb.append(separator).append("gender=").append(gender);
        sb.append(separator).append("birthYear=").append(birthYear);
        sb.append(separator).append("deathYear=").append(deathYear);
        sb.append("]");
        return sb.toString();
    }

}
