/*
 * Created on 2025-02-08 ( 14:50:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.telosys.persistence.entities;

import java.io.Serializable;

/**
 * Composite primary key for entity "Ratings" ( stored in table "ratings" )
 *
 * @author Telosys
 *
 */
public class RatingsId implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY KEY ATTRIBUTES
    private Long bookId;

    private Long userId;

    /**
     * Constructor
     */
    public RatingsId() {
        super();
    }

    /**
     * Constructor with values
     * 
     * @param bookId
     * @param userId
     */
    public RatingsId(Long bookId, Long userId) {
        super();
        this.bookId = bookId;
        this.userId = userId;
    }

    // --- GETTERS & SETTERS FOR KEY FIELDS
    public void setBookId(Long value) {
        this.bookId = value;
    }

    public Long getBookId() {
        return this.bookId;
    }

    public void setUserId(Long value) {
        this.userId = value;
    }

    public Long getUserId() {
        return this.userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        RatingsId other = (RatingsId) obj;
        // --- Attribute bookId
        if (bookId != other.bookId)
            return false;
        // --- Attribute userId
        if (userId != other.userId)
            return false;
        return true;
    }

    @Override
    public String toString() {
        String separator = "|";
        StringBuilder sb = new StringBuilder();
        sb.append("Ratings[");
        sb.append("bookId=").append(bookId);
        sb.append(separator).append("userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }

}
