/*
 * Created on 2025-02-08 ( 14:50:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.telosys.persistence.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;


/**
 * JPA entity class for "Users"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="users", catalog="starter-kit-db" )
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="balance", nullable=false)
    private BigDecimal balance ;

    @Column(name="nickname", nullable=false, length=100)
    private String     nickname ;

    /**
     * Constructor
     */
    public Users() {
		super();
    }
    
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setBalance( BigDecimal balance ) {
        this.balance = balance ;
    }
    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setNickname( String nickname ) {
        this.nickname = nickname ;
    }
    public String getNickname() {
        return this.nickname;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Users[");
		sb.append("id=").append(id);
		sb.append(separator).append("balance=").append(balance);
		sb.append(separator).append("nickname=").append(nickname);
		sb.append("]");
		return sb.toString();
	}

}
