/*
 * Created on 2025-02-08 ( 14:50:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.telosys.rest.controllers;

import java.time.LocalDateTime;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.example.backend.telosys.rest.dto.OrdersDTO;
import com.example.backend.telosys.rest.dto.OrdersResponseDTO;
import com.example.backend.telosys.rest.services.OrdersService;
import com.example.backend.util.Client;

@RestController
@Client
@RequestMapping(value = "/api/v1/orders", produces = MediaType.APPLICATION_JSON_VALUE)
public class OrdersRestController {

	private static final Logger logger = LoggerFactory.getLogger(OrdersRestController.class);

	private OrdersService service; // injected

	/**
	 * Constructor (usable for Dependency Injection)
	 *
	 * @param service
	 */
	protected OrdersRestController(OrdersService service) {
		super();
		this.service = service;
	}

	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<OrdersDTO>> findAll() {
		logger.debug("REST : GET - findAll");
		List<OrdersDTO> list = service.findAll();
		return ResponseEntity.ok(list); // always 200
	}

	/**
	 * Get ONE identified by the given PK
	 *
	 * @param id
	 * @return 200 or 404
	 */
	@GetMapping("/{id}")
	protected ResponseEntity<OrdersDTO> findById(@PathVariable Long id) {
		logger.debug("REST : GET - findById");
		OrdersDTO ordersDTO = service.findById(id);
		if (ordersDTO != null) {
			return ResponseEntity.ok(ordersDTO); // 200 OK, found
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}
	}

	/**
	 * Create if doesn't exist
	 *
	 * @param ordersDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody OrdersDTO ordersDTO) {
		logger.debug("REST : POST - create");
		if (service.create(ordersDTO)) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		} else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param id
	 * @param ordersDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{id}")
	protected ResponseEntity<Void> save(@PathVariable Long id, @RequestBody OrdersDTO ordersDTO) {
		logger.debug("REST : PUT - save");
		service.save(id, ordersDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
	 * Update if exists
	 *
	 * @param ordersDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody OrdersDTO ordersDTO) {
		logger.debug("REST : PUT - update");
		if (service.update(ordersDTO)) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
	 * Partial update for the given PK (if it exists )
	 *
	 * @param id
	 * @param ordersDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{id}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable Long id, @RequestBody OrdersDTO ordersDTO) {
		logger.debug("REST : PATCH - partialUpdate");
		if (service.partialUpdate(id, ordersDTO)) {
			return ResponseEntity.ok().build(); // OK, found and updated
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
	 * Delete by PK
	 *
	 * @param id
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{id}")
	protected ResponseEntity<Void> deleteById(@PathVariable Long id) {
		logger.debug("REST : DELETE - deleteById");
		if (service.deleteById(id)) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

	/**
	 * Buy a book by order ID
	 *
	 * @param id
	 * @return 200 OK or 404 not found
	 */
	@PostMapping("/buybook")
	protected ResponseEntity<OrdersResponseDTO> buyBook(@RequestBody OrdersDTO ordersDTO) {
		logger.debug("REST : POST - buyBook");
		ordersDTO.setOrderedAt(LocalDateTime.now());
		return ResponseEntity.ok(service.buyBook(ordersDTO));
	}
}
