/*
 * Created on 2025-02-08 ( 14:50:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.telosys.rest.controllers;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.example.backend.telosys.rest.dto.RatingsDTO;
import com.example.backend.telosys.rest.services.RatingsService;
import com.example.backend.util.Client;

@RestController
@Client
@RequestMapping(value = "/api/v1/ratings", produces = MediaType.APPLICATION_JSON_VALUE)
public class RatingsRestController {

	private static final Logger logger = LoggerFactory.getLogger(RatingsRestController.class);

	private RatingsService service; // injected

	/**
	 * Constructor (usable for Dependency Injection)
	 *
	 * @param service
	 */
	protected RatingsRestController(RatingsService service) {
		super();
		this.service = service;
	}

	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<RatingsDTO>> findAll() {
		logger.debug("REST : GET - findAll");
		List<RatingsDTO> list = service.findAll();
		return ResponseEntity.ok(list); // always 200
	}

	/**
	 * Get by book ID
	 *
	 * @return
	 */
	@GetMapping("/{bookId}")
	protected ResponseEntity<List<RatingsDTO>> findByBookId(@PathVariable Long bookId) {
		logger.debug("REST : GET - findByBookId");
		List<RatingsDTO> list = service.findByBookId(bookId);
		return ResponseEntity.ok(list); // always 200
	}

	/**
	 * Get ONE identified by the given PK
	 *
	 * @param bookId
	 * @param userId
	 * @return 200 or 404
	 */
	@GetMapping("/{bookId}/{userId}")
	protected ResponseEntity<RatingsDTO> findById(@PathVariable Long bookId, @PathVariable Long userId) {
		logger.debug("REST : GET - findById");
		RatingsDTO ratingsDTO = service.findById(bookId, userId);
		if (ratingsDTO != null) {
			return ResponseEntity.ok(ratingsDTO); // 200 OK, found
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}
	}

	/**
	 * Create if doesn't exist
	 *
	 * @param ratingsDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody RatingsDTO ratingsDTO) {
		logger.debug("REST : POST - create");
		if (service.create(ratingsDTO)) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		} else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param bookId
	 * @param userId
	 * @param ratingsDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{bookId}/{userId}")
	protected ResponseEntity<Void> save(@PathVariable Long bookId, @PathVariable Long userId,
			@RequestBody RatingsDTO ratingsDTO) {
		logger.debug("REST : PUT - save");
		service.save(bookId, userId, ratingsDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
	 * Update if exists
	 *
	 * @param ratingsDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody RatingsDTO ratingsDTO) {
		logger.debug("REST : PUT - update");
		if (service.update(ratingsDTO)) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
	 * Partial update for the given PK (if it exists )
	 *
	 * @param bookId
	 * @param userId
	 * @param ratingsDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{bookId}/{userId}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable Long bookId, @PathVariable Long userId,
			@RequestBody RatingsDTO ratingsDTO) {
		logger.debug("REST : PATCH - partialUpdate");
		if (service.partialUpdate(bookId, userId, ratingsDTO)) {
			return ResponseEntity.ok().build(); // OK, found and updated
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
	 * Delete by PK
	 *
	 * @param bookId
	 * @param userId
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{bookId}/{userId}")
	protected ResponseEntity<Void> deleteById(@PathVariable Long bookId, @PathVariable Long userId) {
		logger.debug("REST : DELETE - deleteById");
		if (service.deleteById(bookId, userId)) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
