/*
 * Created on 2025-02-20 ( 20:11:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.telosys.rest.controllers;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.example.backend.telosys.rest.dto.ShippingInfoDTO;
import com.example.backend.telosys.rest.services.ShippingInfoService;
import com.example.backend.util.Client;

import jakarta.validation.ConstraintViolationException;

@RestController
@Client
@RequestMapping(value = "/api/v1/shippinginfo", produces = MediaType.APPLICATION_JSON_VALUE)
public class ShippingInfoRestController {

	private static final Logger logger = LoggerFactory.getLogger(ShippingInfoRestController.class);

	private ShippingInfoService service; // injected

	/**
	 * Constructor (usable for Dependency Injection)
	 *
	 * @param service
	 */
	protected ShippingInfoRestController(ShippingInfoService service) {
		super();
		this.service = service;
	}

	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<ShippingInfoDTO>> findAll() {
		logger.debug("REST : GET - findAll");
		List<ShippingInfoDTO> list = service.findAll();
		return ResponseEntity.ok(list); // always 200
	}

	/**
	 * Get ONE identified by the given PK
	 *
	 * @param id
	 * @return 200 or 404
	 */
	@GetMapping("/{id}")
	protected ResponseEntity<ShippingInfoDTO> findById(@PathVariable long id) {
		logger.debug("REST : GET - findById");

		ShippingInfoDTO shippingInfoDTO = service.findById(id);
		if (shippingInfoDTO != null) {
			return ResponseEntity.ok(shippingInfoDTO); // 200 OK, found
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}
	}

	/**
	 * Get ALL by userId
	 *
	 * @param userId
	 * @return 200 or 404
	 */
	@GetMapping("user/{userId}")
	protected ResponseEntity<List<ShippingInfoDTO>> findByUserId(@PathVariable long userId) {
		logger.debug("REST : GET - findByUserId");
		List<ShippingInfoDTO> shippingInfoList = service.findByUserId(userId);
		if (shippingInfoList != null && !shippingInfoList.isEmpty()) {
			return ResponseEntity.ok(shippingInfoList); // 200 OK, found
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}
	}

	/**
	 * Create if doesn't exist
	 *
	 * @param shippingInfoDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody ShippingInfoDTO shippingInfoDTO) {
		logger.debug("REST : POST - create");
		try {
			if (service.create(shippingInfoDTO)) {
				return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
			} else {
				return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
			}
		} catch (ConstraintViolationException e) {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param id
	 * @param shippingInfoDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{id}")
	protected ResponseEntity<Void> save(@PathVariable long id, @RequestBody ShippingInfoDTO shippingInfoDTO) {
		logger.debug("REST : PUT - save");
		service.save(id, shippingInfoDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
	 * Update if exists
	 *
	 * @param shippingInfoDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody ShippingInfoDTO shippingInfoDTO) {
		logger.debug("REST : PUT - update");
		if (service.update(shippingInfoDTO)) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
	 * Partial update for the given PK (if it exists )
	 *
	 * @param id
	 * @param shippingInfoDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{id}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable long id, @RequestBody ShippingInfoDTO shippingInfoDTO) {
		logger.debug("REST : PATCH - partialUpdate");
		if (service.partialUpdate(id, shippingInfoDTO)) {
			return ResponseEntity.ok().build(); // OK, found and updated
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
	 * Delete by PK
	 *
	 * @param id
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{id}")
	protected ResponseEntity<Void> deleteById(@PathVariable long id) {
		logger.debug("REST : DELETE - deleteById");
		if (service.deleteById(id)) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		} else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
