/*
 * Created on 2025-02-08 ( 14:50:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.telosys.rest.dto;

import java.io.Serializable;

/**
 * DTO class for "Authors"
 *
 * @author Telosys
 *
 */
public class AuthorsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private String name ;
    private Boolean gender ;
    private Short birthYear ;
    private Short deathYear ;

    /**
     * Constructor
     */
    public AuthorsDTO() {
		super();
    }
    

    public AuthorsDTO(Long id, String name) {
        this.id = id;
        this.name = name;
    }


    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setGender( Boolean gender ) {
        this.gender = gender ;
    }
    public Boolean getGender() {
        return this.gender;
    }

    public void setBirthYear( Short birthYear ) {
        this.birthYear = birthYear ;
    }
    public Short getBirthYear() {
        return this.birthYear;
    }

    public void setDeathYear( Short deathYear ) {
        this.deathYear = deathYear ;
    }
    public Short getDeathYear() {
        return this.deathYear;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Authors[");
		sb.append("id=").append(id);
		sb.append(separator).append("name=").append(name);
		sb.append(separator).append("gender=").append(gender);
		sb.append(separator).append("birthYear=").append(birthYear);
		sb.append(separator).append("deathYear=").append(deathYear);
		sb.append("]");
		return sb.toString();
	}
}
