/*
 * Created on 2025-02-08 ( 14:50:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.telosys.rest.dto;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * DTO class for "Orders"
 *
 * @author Telosys
 *
 */
public class OrdersDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long bookId ;
    private Long userId ;
    private byte quality ;
    private LocalDateTime orderedAt ;
    //--- LINKS ( RELATIONSHIPS )
    private BooksDTO books ; 
    private UserDTO users ; 

    /**
     * Constructor
     */
    public OrdersDTO() {
		super();
    }
    
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setBookId( Long bookId ) {
        this.bookId = bookId ;
    }
    public Long getBookId() {
        return this.bookId;
    }

    public void setUserId( Long userId ) {
        this.userId = userId ;
    }
    public Long getUserId() {
        return this.userId;
    }

    public void setQuality( byte quality ) {
        this.quality = quality ;
    }
    public byte getQuality() {
        return this.quality;
    }

    public void setOrderedAt( LocalDateTime orderedAt ) {
        this.orderedAt = orderedAt ;
    }
    public LocalDateTime getOrderedAt() {
        return this.orderedAt;
    }

    public BooksDTO getBooks() {
        return this.books;
    } 

    public UserDTO getUser() {
        return this.users;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Orders[");
		sb.append("id=").append(id);
		sb.append(separator).append("bookId=").append(bookId);
		sb.append(separator).append("userId=").append(userId);
		sb.append(separator).append("quality=").append(quality);
		sb.append(separator).append("orderedAt=").append(orderedAt);
		sb.append("]");
		return sb.toString();
	}
}
