/*
 * Created on 2025-02-20 ( 20:11:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.telosys.rest.dto;

import java.io.Serializable;
import java.time.LocalDateTime;

import com.example.backend.util.Client;

/**
 * DTO class for "ShippingInfo"
 *
 * @author Telosys
 *
 */
@Client
public class ShippingInfoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- PRIMARY KEY
    private long id;
    // --- OTHER DATA FIELDS
    private LocalDateTime createdAt;
    private int disctrictId;
    private String name;
    private String phoneNumber;
    private int provinceId;
    private int wardCode;
    private Long userId;
    private String address;
    // --- LINKS ( RELATIONSHIPS )
    private UserDTO user;

    /**
     * Constructor
     */
    public ShippingInfoDTO() {
        super();
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getId() {
        return this.id;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setDisctrictId(int disctrictId) {
        this.disctrictId = disctrictId;
    }

    public int getDisctrictId() {
        return this.disctrictId;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setProvinceId(int provinceId) {
        this.provinceId = provinceId;
    }

    public int getProvinceId() {
        return this.provinceId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return this.userId;
    }

    public UserDTO getUser() {
        return this.user;
    }

    @Override
    public String toString() {
        String separator = "|";
        StringBuilder sb = new StringBuilder();
        sb.append("ShippingInfo[");
        sb.append("id=").append(id);
        sb.append(separator).append("createdAt=").append(createdAt);
        sb.append(separator).append("disctrictId=").append(disctrictId);
        sb.append(separator).append("name=").append(name);
        sb.append(separator).append("phoneNumber=").append(phoneNumber);
        sb.append(separator).append("provinceId=").append(provinceId);
        sb.append(separator).append("userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }

    public int getWardCode() {
        return wardCode;
    }

    public void setWardCode(int wardCode) {
        this.wardCode = wardCode;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

}
