/*
 * Created on 2025-02-08 ( 14:50:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.telosys.rest.dto;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * DTO class for "User"
 *
 * @author Telosys
 *
 */
public class UserDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- PRIMARY KEY
    private Long id;
    // --- OTHER DATA FIELDS
    private BigDecimal balance;
    private String firstName;
    private String lastName;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Constructor
     */
    public UserDTO() {
        super();
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return this.id;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    @Override
    public String toString() {
        String separator = "|";
        StringBuilder sb = new StringBuilder();
        sb.append("User[");
        sb.append("id=").append(id);
        sb.append(separator).append("balance=").append(balance);
        sb.append("]");
        return sb.toString();
    }
}
