/*
 * Created on 2025-02-08 ( 14:50:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.example.backend.telosys.rest.dto;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * DTO class for "Users"
 *
 * @author Telosys
 *
 */
public class UsersDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private BigDecimal balance ;
    private String nickname ;

    /**
     * Constructor
     */
    public UsersDTO() {
		super();
    }
    
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setBalance( BigDecimal balance ) {
        this.balance = balance ;
    }
    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setNickname( String nickname ) {
        this.nickname = nickname ;
    }
    public String getNickname() {
        return this.nickname;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Users[");
		sb.append("id=").append(id);
		sb.append(separator).append("balance=").append(balance);
		sb.append(separator).append("nickname=").append(nickname);
		sb.append("]");
		return sb.toString();
	}
}
