package com.example.backend.thirtParty.telosys.persistence.entities;

/*
 * Created on 2025-02-08 ( 14:50:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */

import java.io.Serializable;
import java.time.LocalDateTime;

import org.springframework.data.annotation.CreatedDate;

import com.example.backend.thirtParty.telosys.rest.dto.ShippingInfoDTO;
import com.example.backend.users.User;
import com.example.backend.util.Client;

import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Pattern;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Books"
 *
 * @author Telosys
 *
 */
@Entity
@Client
@Table(name = "shipping_info", catalog = "starter-kit-db")
@NoArgsConstructor
public class ShippingInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name = "id", nullable = false)
    private Long id;

    // --- OTHER DATA FIELDS
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    @Column(name = "phone_number", nullable = false, unique = true)
    @Pattern(regexp = "^\\+?[0-9]{10,15}$", message = "Invalid phone number format")
    private String phoneNumber;

    @Column(name = "province_id", nullable = false)
    private int provinceId;

    @Column(name = "disctrict_id", nullable = false)
    private int disctrictId;

    @Column(name = "wardCode", nullable = false)
    private int wardCode;

    @Column(name = "address", nullable = false)
    private String address;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @CreatedDate
    @Nullable
    private LocalDateTime createdAt;
    // --- LINKS ( RELATIONSHIPS )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", referencedColumnName = "id", insertable = false, updatable = false)
    private User users;

    public ShippingInfo(ShippingInfoDTO dto) {
        this.name = dto.getName();
        this.phoneNumber = dto.getPhoneNumber();
        this.provinceId = dto.getProvinceId();
        this.disctrictId = dto.getDisctrictId();
        this.wardCode = dto.getWardCode();
        this.address = dto.getAddress();
        this.userId = dto.getUserId();
        this.createdAt = dto.getCreatedAt();
    }

    @Override
    public String toString() {
        return "ShippingInfo [id=" + id + ", name=" + name + ", phoneNumber=" + phoneNumber + ", provinceId="
                + provinceId + ", disctrictId=" + disctrictId + ", wardCode=" + wardCode + ", address=" + address
                + ", userId=" + userId + ", createdAt=" + createdAt + "]";
    }

    public static long getSerialversionuid() {
        return serialVersionUID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public int getProvinceId() {
        return provinceId;
    }

    public void setProvinceId(int provinceId) {
        this.provinceId = provinceId;
    }

    public int getDisctrictId() {
        return disctrictId;
    }

    public void setDisctrictId(int disctrictId) {
        this.disctrictId = disctrictId;
    }

    public int getWardCode() {
        return wardCode;
    }

    public void setWardCode(int wardCode) {
        this.wardCode = wardCode;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public User getUsers() {
        return users;
    }

    public void setUsers(User users) {
        this.users = users;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

}
